### PR TITLE
Backlink Obelous.com

### PR DESCRIPTION
**Pull request by BitesizedLion**
ty

### CODE REVIEW

**Comment by TrainerGamer** [comment]
Please could you explain why you would like it to be linked to obelous.com as opposed to your GitHub.

**Comment by BitesizedLion** [comment]
> Please could you explain why you would like it to be linked to obelous.com as opposed to your GitHub.

because its better

**Comment by TrainerGamer** [comment]
If you don't provide a valid reason I can't really see any point in merging this - obelous.com isn't relevant to this project whereas your GitHub is.

**Comment by BitesizedLion** [comment]
> If you don't provide a valid reason I can't really see any point in merging this - obelous.com isn't relevant to this project whereas your GitHub is.

It's relevant, because it's me.

**Comment by TrainerGamer** [comment]
Your GitHub is what this project is based on whereas your site is a mostly content-less default website template. For now, I'm going to go ahead and close this, however, if you turn your site into something more meaningful (portfolio or similar) then I would be happy to re-open this.

**Comment by BitesizedLion** [comment]
> Your GitHub is what this project is based on whereas your site is a mostly content-less default website template. For now, I'm going to go ahead and close this, however, if you turn your site into something more meaningful (portfolio or similar) then I would be happy to re-open this.

That's what is happening, so merge it.

**Comment by TrainerGamer** [comment]
Once it has something meaningful on it, then I will happily consider it.

**Comment by BitesizedLion** [comment]
> Once it has something meaningful on it, then I will happily consider it.

it has my life on it so its meaningful

**Comment by TrainerGamer** [comment]
@BitesizedLion has since made changes to his site - [obelous.com](https://obelous.com)

Therefore I'm going to go ahead and merge this :)

**Pull request merged**
